// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'NewsletterSubscribe': typeof import('../components/NewsletterSubscribe.vue')['default'],
    'TheFooter': typeof import('../components/TheFooter.vue')['default'],
    'TheHeader': typeof import('../components/TheHeader.vue')['default'],
    'TheHero': typeof import('../components/TheHero.vue')['default'],
    'TheSlider': typeof import('../components/TheSlider.vue')['default'],
    'NuxtWelcome': typeof import('../node_modules/nuxt3/dist/app/components/nuxt-welcome.vue')['default'],
    'ClientOnly': typeof import('../node_modules/nuxt3/dist/app/components/client-only')['default']
  }
}
export {}
